# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
    # Build
    - name: Build with Gradle
      run: ./gradlew clean build

    # 전송할 파일을 담을 디렉토리 생성
    - name: Make Directory for deliver
      run: mkdir deploy

    # Jar 파일 Copy
    - name: Copy Jar
      run: cp ./build/libs/*.jar ./deploy/

    # 압축파일 형태로 전달
    - name: Make zip file
      run: zip -r -qq -j ./springboot-intro-build.zip ./deploy

    # S3 Bucket으로 copy
    - name: Deliver to AWS S3
      env:
        AWS_ACCESS_KEY_ID: AKIAWUPSDUHNZRMYVSGY
        # AWS_ACCESS_KEY_ID: ${{'{{' }} secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: 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
        # AWS_SECRET_ACCESS_KEY: ${{'{{' }} secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 cp \
        --region ap-northeast-2 \
        --acl private ./springboot-intro-build.zip s3://github-action-whahn/
        
    # Deploy
    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: AKIAWUPSDUHNZRMYVSGY
        # AWS_ACCESS_KEY_ID: ${{'{{' }} secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: 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
        # AWS_SECRET_ACCESS_KEY: ${{'{{' }} secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws deploy create-deployment \
        --application-name github-action-test \
        --deployment-group-name test \
        --file-exists-behavior OVERWRITE \
        --s3-location bucket=springboot-intro-build,bundleType=zip,key=springboot-intro-build.zip \
        --region ap-northeast-2

  # 
